config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pictures do
    collection do
      post :uppos
    end
  end

  root 'main#index'
  get 'contacts' => 'main#contacts'
  get 'about' => 'main#about'
  get 'admin' => 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @pictures = Picture.order('position ASC')
  end

  def contacts
  end

  def about
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /pictures
  # GET /pictures.json
  def index
    #@pictures = Picture.all
    @pictures = Picture.order('position ASC')
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show

    #render plain: @myimage
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        create_image_tumb(@picture)

        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def uppos

    pic_hash = {}
    i = 0
    params.each do |key, value|
      if (numeric? key)
        i +=1
        pic_hash[key] = i
      end
    end

    pic_hash.each do |p|
      #puts p
      pic = Picture.find(p[0])
      pic.position = p[1]
      pic.save
      #logger.info(p)
    end
    redirect_to action: 'index', controller: 'pictures'
    #render plain: pic_hash
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        create_image_tumb(@picture)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def numeric? n
      Float(n) != nil rescue false
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :description, :image)
    end

    def create_image_tumb img
      @myimage = MiniMagick::Image.open(@picture.image.path)
      @myimage.resize "200x300"
      file_path_dir = File.dirname(@picture.image.path)
      file_ext = File.extname(@picture.image.path)
      file_name = File.basename(@picture.image.path, file_ext)
      file_name_mini = file_name + "_tumb" + file_ext
      mini_file = File.join(file_path_dir, file_name_mini)
      FileUtils.cp @myimage.path, mini_file
      #@picture.image_file_name_mini = file_name_mini

      @image_tumb = File.dirname(@picture.image.url) + '/' + File.basename(@picture.image.url, File.extname(@picture.image.url)) + '_tumb' + File.extname(@picture.image.url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/url_image_helper.rb
module UrlImageHelper
  def hello
    "hello"
  end

  def UrlImageTumb url
    File.dirname(url) + '/' + File.basename(url, File.extname(url)) + '_tumb' + File.extname(url)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Max Konyshev" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
    <script>
      $(document).foundation();
      $(document).ready(function() {

          /* This is basic - uses default settings */

          $("a#single_image").fancybox();

          /* Using custom settings */

          $("a#inline").fancybox({
              'hideOnContentClick': true
          });

          /* Apply fancybox to multiple items */

          $("a.group").fancybox({
              'transitionIn'	:	'elastic',
              'transitionOut'	:	'elastic',
              'speedIn'		:	600,
              'speedOut'		:	200,
              'overlayShow'	:	false
          });

      });
    </script>
  </body>
</html>

app/views/main/about.html.erb
<div id="top" class="row">
  <div id="left" class="small-3 columns">
    <u><%= link_to 'About', about_path, id: 'a_abo' %></u>
  </div>
  <div id="center" class="small-6 columns">
    Max Konyshev
  </div>
  <div id="right" class="small-3 columns">
    <%= link_to 'Contacts', contacts_path, id: 'a_con' %>
  </div>
</div>

<div id="gal" class="row">
  <div class="small-3 small-centered columns">
    <%= link_to 'Gallery', root_path, id: 'a_gal' %>
  </div>
</div>

<div id="hr" class="row">
  <div class="small-12 columns">
    <hr />
  </div>
</div>

<div class="row">
  <div id="nav" class="small-12 columns">

  </div>
</div>

<style>

#a_gal {
  padding: 8px;
}

#a_gal:hover {
  padding: 8px;
  color: #fff;
  background-color: #000;
}

#a_con {
  padding: 8px;
}

#a_con:hover {
  padding: 8px;
  color: #fff;
  background-color: #000;
}

#a_abo {
  padding: 8px;
}

#a_abo:hover {
  padding: 8px;
  color: #fff;
  background-color: #000;
}

.copyright {
    font-size: 12px;
    text-align: center;
    color: grey;
}

.th {
  margin: 10px;
}

#hr {
  padding-top: 30px;
  padding-bottom: 30px;
  /* Gradient transparent - color - transparent */
}

hr {
  border: 0;
  height: 1px;
  background-image: -webkit-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
  background-image:    -moz-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
  background-image:     -ms-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
  background-image:      -o-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
}

#gal {
  font-family: 'i_still_knowregular';
  font-size: 18px;
  text-align: center;
  padding-bottom: 40px;
}

#top {
  padding-top: 120px;
  padding-bottom: 40px;
}

#left {
  text-align: right;
  font-family: 'i_still_knowregular';
  font-size: 18px;
}

#center {
  font-family: 'i_still_knowregular';
  font-size: 48px;
  text-align: center;
}

#right {
  text-align: left;
  font-family: 'i_still_knowregular';
  font-size: 18px;
}
</style>

<div id="hr" class="row">
  <div class="small-12 columns">
    <hr />
  </div>
</div>

<div id="footer" class="row">
  <div class="small-3 small-centered columns">
    <p class="copyright">Max Konyshev 2015</p>
  </div>
</div>

<script>
$(document).foundation();
$(document).ready(function() {

	/* This is basic - uses default settings */

	$("a#single_image").fancybox();

	/* Using custom settings */

	$("a#inline").fancybox({
		'hideOnContentClick': true
	});

	/* Apply fancybox to multiple items */

	$("a.group").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600,
		'speedOut'		:	200,
		'overlayShow'	:	false
	});

});
</script>

app/views/main/contacts.html.erb
<div id="top" class="row">
  <div id="left" class="small-3 columns">
    <%= link_to 'About', about_path, id: 'a_abo' %>
  </div>
  <div id="center" class="small-6 columns">
    Max Konyshev
  </div>
  <div id="right" class="small-3 columns">
    <u><%= link_to 'Contacts', contacts_path, id: 'a_con' %></u>
  </div>
</div>

<div id="gal" class="row">
  <div class="small-3 small-centered columns">
    <%= link_to 'Gallery', root_path, id: 'a_gal' %>
  </div>
</div>

<div id="hr" class="row">
  <div class="small-12 columns">
    <hr />
  </div>
</div>

<div class="row">
  <div id="nav" class="small-12 columns">

  </div>
</div>

<style>

    #a_gal {
        padding: 8px;
    }

    #a_gal:hover {
        padding: 8px;
        color: #fff;
        background-color: #000;
    }

    #a_con {
        padding: 8px;
    }

    #a_con:hover {
        padding: 8px;
        color: #fff;
        background-color: #000;
    }

    #a_abo {
        padding: 8px;
    }

    #a_abo:hover {
        padding: 8px;
        color: #fff;
        background-color: #000;
    }

    .copyright {
        font-size: 12px;
        text-align: center;
        color: grey;
    }

    .th {
        margin: 10px;
    }

    #hr {
        padding-top: 30px;
        padding-bottom: 30px;
        /* Gradient transparent - color - transparent */
    }

    hr {
        border: 0;
        height: 1px;
        background-image: -webkit-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
        background-image:    -moz-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
        background-image:     -ms-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
        background-image:      -o-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
    }

    #gal {
        font-family: 'i_still_knowregular';
        font-size: 18px;
        text-align: center;
        padding-bottom: 40px;
    }

    #top {
        padding-top: 120px;
        padding-bottom: 40px;
    }

    #left {
        text-align: right;
        font-family: 'i_still_knowregular';
        font-size: 18px;
    }

    #center {
        font-family: 'i_still_knowregular';
        font-size: 48px;
        text-align: center;
    }

    #right {
        text-align: left;
        font-family: 'i_still_knowregular';
        font-size: 18px;
    }
</style>

<div id="hr" class="row">
  <div class="small-12 columns">
    <hr />
  </div>
</div>

<div id="footer" class="row">
  <div class="small-3 small-centered columns">
    <p class="copyright">Max Konyshev 2015</p>
  </div>
</div>

<script>
    $(document).foundation();
    $(document).ready(function() {

        /* This is basic - uses default settings */

        $("a#single_image").fancybox();

        /* Using custom settings */

        $("a#inline").fancybox({
            'hideOnContentClick': true
        });

        /* Apply fancybox to multiple items */

        $("a.group").fancybox({
            'transitionIn'	:	'elastic',
            'transitionOut'	:	'elastic',
            'speedIn'		:	600,
            'speedOut'		:	200,
            'overlayShow'	:	false
        });

    });
</script>

app/views/main/index.html.erb
<div id="top" class="row">
  <div id="left" class="small-3 columns">
    <%= link_to 'About', about_path, id: 'a_abo' %>
  </div>
  <div id="center" class="small-6 columns">
    Max Konyshev
  </div>
  <div id="right" class="small-3 columns">
    <%= link_to 'Contacts', contacts_path, id: 'a_con' %>
  </div>
</div>

<div id="gal" class="row">
  <div class="small-3 small-centered columns">
    <u><%= link_to 'Gallery', root_path, id: 'a_gal' %></u>
  </div>
</div>

<div id="hr" class="row">
  <div class="small-12 columns">
    <hr />
  </div>
</div>

<div class="row">
  <div id="nav" class="small-12 columns">
    <% @pictures.each do |p| %>
      <a id="single_image" class="th" href="<%= p.image.url %>">
        <%= image_tag UrlImageTumb(p.image.url) %>
      </a>
    <% end %>
  </div>
</div>

<style>

#a_gal {
  padding: 8px;
}

#a_gal:hover {
  padding: 8px;
  color: #fff;
  background-color: #000;
}

#a_con {
  padding: 8px;
}

#a_con:hover {
  padding: 8px;
  color: #fff;
  background-color: #000;
}

#a_abo {
  padding: 8px;
}

#a_abo:hover {
  padding: 8px;
  color: #fff;
  background-color: #000;
}

.copyright {
    font-size: 12px;
    text-align: center;
    color: grey;
}

.th {
  margin: 10px;
}

#hr {
  padding-top: 30px;
  padding-bottom: 30px;
  /* Gradient transparent - color - transparent */
}

hr {
  border: 0;
  height: 1px;
  background-image: -webkit-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
  background-image:    -moz-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
  background-image:     -ms-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
  background-image:      -o-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
}

#gal {
  font-family: 'i_still_knowregular';
  font-size: 18px;
  text-align: center;
  padding-bottom: 40px;
}

#top {
  padding-top: 120px;
  padding-bottom: 40px;
}

#left {
  text-align: right;
  font-family: 'i_still_knowregular';
  font-size: 18px;
}

#center {
  font-family: 'i_still_knowregular';
  font-size: 48px;
  text-align: center;
}

#right {
  text-align: left;
  font-family: 'i_still_knowregular';
  font-size: 18px;
}
</style>

<div id="hr" class="row">
  <div class="small-12 columns">
    <hr />
  </div>
</div>

<div id="footer" class="row">
  <div class="small-3 small-centered columns">
    <p class="copyright">Max Konyshev 2015</p>
  </div>
</div>

<script>
$(document).ready(function() {

	/* This is basic - uses default settings */

	$("a#single_image").fancybox();

	/* Using custom settings */

	$("a#inline").fancybox({
		'hideOnContentClick': true
	});

	/* Apply fancybox to multiple items */

	$("a.group").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600,
		'speedOut'		:	200,
		'overlayShow'	:	false
	});

});
</script>

app/views/pictures/____index.html.erb
<div class="row">
  <div class="small-11 small-centered columns">
    <p id="notice"><%= notice %></p>
    <form id="update_position" action="pictures/update">
      <input type="submit">
      <div id="sortable">
        <% @pictures.each do |picture| %>
            <div class="imblock">
              <%= image_tag UrlImageTumb(picture.image.url), class: "th" %>
              <div class="dimg"><%= link_to 'Show', picture %></div>
              <div class="dimg"><%= link_to 'Edit', edit_picture_path(picture) %></div>
            </div>
        <% end %>
      </div>
    </form>
  </div>




<div class="row">
  <div class="small-6 small-centered columns">
    <p id="notice"><%= notice %></p>

    <h1>Listing Pictures</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pictures.each do |picture| %>
          <tr>
            <td><%= picture.name %></td>
            <td><%= picture.description %></td>
            <td><%= link_to 'Show', picture %></td>
            <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
            <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Picture', new_picture_path %>
  </div>
</div>

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => { :multipart => true }) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<div class="row">
  <div class="small-6 small-centered columns">
    <h1>Editing Picture</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @picture %> |
    <%= link_to 'Back', pictures_path %>
  </div>
</div>

app/views/pictures/index.html.erb
<%= form_for :pictures, :url => uppos_pictures_path do |f| %>
<div data-magellan-expedition="fixed">
  <dl class="sub-nav">
    <dd data-magellan-arrival="build"><p style="font-family: i_still_knowregular; font-size: larger">Max Konyshev</p></dd>
    <dd data-magellan-arrival="js"><%= f.submit  'Обновить позиции', :class => 'button tiny success' %></dd>
    <dd data-magellan-arrival="js"><%= link_to 'Выход', destroy_user_session_path, method: :delete, :class => 'button tiny alert' %></dd>
  </dl>
</div>
<div class="row">
  <div class="small-12 small-centered columns">
        <p id="notice"><%= notice %></p>



            <div id="sortable">
              <% @pictures.each do |picture| %>
                  <div class="imblock">
                    <%= hidden_field_tag picture.id, :id %>
                    <%= image_tag UrlImageTumb(picture.image.url), class: "th" %>
                    <!--<div class="dimg">< link_to 'Show', picture %></div>-->
                    <!--<div class="dimg">< link_to 'Edit', edit_picture_path(picture) %></div>-->
                  </div>
              <% end %>
            </div>
        <% end %>
  </div>
</div>

<style>
  .imblock {
      width: 200px;
      height: 320px;
      margin: 15px;
      /*border: 1px solid grey;*/
      align-items: center;
      float: left;
  }

  .dimg {
      width: 200px;
      height: 30px;
      float: left;
  }
    #sortable div {
        float: left;
        margin: 10px;
    }
</style>

<script>
    $(function() {
        $( "#sortable" ).sortable();
        $( "#sortable" ).disableSelection();
    });
</script>

app/views/pictures/new.html.erb
<div class="row">
  <div class="small-6 small-centered columns">
    <h1>New Picture</h1>

    <%= render 'form' %>

    <%= link_to 'Back', pictures_path %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="row">
  <div class="small-6 small-centered columns">
    <p id="notice"><%= notice %></p>

    <p>
      <%= image_tag @image_tumb %>

    </p>
    <p>
      <strong>Name:</strong>
      <%= @picture.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @picture.description %>
    </p>

    <%= link_to 'Edit', edit_picture_path(@picture) %> |
    <%= link_to 'Back', pictures_path %>
  </div>
</div>